apiVersion: v1
kind: Service
metadata:
  name: smart-factory-consumer
  labels:
    app.kubernetes.io/name: smart-factory-consumer
    app.kubernetes.io/part-of: smart-factory-monitor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smart-factory-consumer
  ports:
    - name: monitoring
      port: 8000
      targetPort: monitoring
