apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-factory-models
  labels:
    app.kubernetes.io/part-of: smart-factory-monitor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
